### ISSUE TITLE
Debian 12 and 11 (Bookworm -Bullseye) add-apt-repository causes error

### ISSUE THREAD

**Issue by cerebrux** [Utappia/uCareSystem#84]
On Debian 12

```
Adding Utappia repository
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
dpkg: error processing package ucaresystem-core (--configure):
```
I need to update this line 
https://github.com/Utappia/uCareSystem/blob/1243e83e89c06c4affaf1b231322559cb8de05ff/assets/postinst#L15

**Comment by cerebrux** [comment]
fixed in https://github.com/Utappia/uCareSystem/commit/295112d10297cb16b52fbc193ede2b286562de9f
